'@Only
'@TestSuite IOCMT IOCMixinTests

namespace IOCMT

function init()
  registerLogger("ObservableTests")
end function

'@BeforeEach
function BeforeEach()
  logInfo("beforeEach")
  MIOC.cleanup()
end function

'+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
'@It tests getInstance
'+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

'@Test descriptors have not been created
function namespace_itGroup_testName()
  m.Fail("implement me!")
  descriptor = {
      "id": "authModule",
      "type": "node",
      "subType": "AuthModule",
      "dependencies": {
        "requestModule": "request",
        "networkModule": "network",
        "netTimeout": "timeout"
      }
    }
    ? descriptor
end function

end namespace