'@TestSuite IOCMT IOCMixinTests

namespace IOCMT

function init()
  registerLogger("ObservableTests")
end function

'@BeforeEach
function BeforeEach()
  logInfo("beforeEach")
  MIOC.cleanup()
end function

'+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
'@It tests getInstance
'+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

'@Test descriptors have not been created
function namespace_itGroup_testName()
  m.Fail("implement me!")
  descriptor = {
    "id": "authModule"
    "type": "node"
    "subType": "AuthModule"
    "dependencies": {
      "requestModule": "request"
      "networkModule": "network"
      "netTimeout": "timeout"
    }
  }
  
  ' map = {
  '   "AuthModule": IOCMT_MockAuthModule
  '   "IOCMixinTests": getFunctions_IOCMixinTests 
  '   ' "ObservableTests": getFunctions_ObservableTests 
  '   ' "BaseObservableTests": getFunctions_BaseObservableTests 
  '   ' "BaseViewModelTests": getFunctions_BaseViewModelTests 
  '   ' "ObservableMixinTests": getFunctions_ObservableMixinTests 
  '   ' "TestViewModel": getFunctions_TestViewModel 
  '   ' "ViewModelMixinTests": getFunctions_ViewModelMixinTests 
  ' }
  ' m.foo = IOCMT_MockAuthModule
  ' m.bar = NOT_THERE
  ' ? descriptor
end function

end namespace

function MockAuthModule()
  return {
    "class": "authModule"
  }
end function