'@TestSuite IOCMT IOCMixinTests

namespace IOCMT

function init()
  registerLogger("ObservableTests")
end function

'@BeforeEach
function BeforeEach()
  logInfo("beforeEach")
  MIOC.cleanup()
end function

'+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
'@It tests createContainer
'+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

'@Test descriptors have not been created
function createContainer_valid()
  container = TU.loadFile("pkg:/source/tests/maestro/ioc/simple-container.json")
  MIOC.createContainer(container)

  m.assertEqual(m.global._mioc_descriptors, container.resources)
end function

end namespace
