'@TestSuite [MBVMT] BaseViewModel Tests
namespace MBVMT

'@BeforeEach
function BeforeEach()
end function

'+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
'@It tests simple constructor
'+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

'@Test invalid
'@Params[invalid]
'@Params[{}]
'@Params["wrong"]
'@Params[[]]
'@Params[{"prop":invalid}]
'@Params[{"name":""}]
function constructor_invalid(subClass)
  vm = BaseViewModel()
  m.assertEqual(vm.state, "invalid")
end function

'+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
'@It tests vm class functions correctly, with scoped methods
'+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

'@Test valid
function testVM()
  vm = TestViewModel()
  m.assertEqual(vm.state, "none")
  m.assertEqual(vm.name, "testVM")

  vm.initialize()
  m.assertEqual(vm.state, "initialized")

  vm.setAge(23)
  m.assertEqual(vm.getAge(), 23)
end function

'@Test calls abstract methods
function testVM_abstractMethods()
  vm = TestViewModel()
  m.assertEqual(vm.state, "none")
  m.assertEqual(vm.name, "testVM")

  vm.initialize()
  m.assertEqual(vm.state, "initialized")
  m.assertTrue(vm.isInitCalled)

  vm.onShow()
  m.assertTrue(vm.isOnShowCalled)

  vm.onHide()
  m.assertTrue(vm.isOnHideCalled)

  vm.destroy()
  m.assertTrue(vm.isDestroyCalled)
end function

'@Test timeConstructor
function timeConstructor()
  vm = TestViewModel()
end function

'@Test time method calls
function testVM_time()
  vm = TestViewModel()
  vm.initialize()
  vm.onShow()
  vm.onHide()
  vm.destroy()
end function

end namespace