namespace TVM
class TestViewModel extends BaseViewModel

public function new(name)
  m.super(name)
end function

public function getAge()
  return m.age
end function

public function setAge(age)
  return m.setField("age", age)
end function

public function _initialize()
  m.isInitCalled = true
end function

override private function onShow()
  m.isOnShowCalled = true
end function

override private function onHide()
  m.isOnHideCalled = true
end function

override private function destroy()
  m.isDestroyCalled = true
end function

end class
end namespace