'@TestSuite [VMMT] ViewModelMixin Tests

namespace MVMMT

'@BeforeEach
function BeforeEach()
  m.node.delete("focusMap")
  m.node.delete("one")
  m.node.delete("two")
  m.node.delete("three")
end function

'+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
'@It tests isVM
'+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
'@Test invalid
'@Params[invalid]
'@Params[{}]
'@Params["wrong"]
'@Params[[]]
'@Params[{"prop":invalid}]
'@Params[{"name":""}]
function isVM_invalid(vm)
  m.assertFalse(MVMM.isVM(vm))
end function

function isVM_bogusVM()
  m.assertFalse(MVMM.isVM({"__viewModel": true}))
end function

function isVM_valid()
  m.assertTrue(MVMM.isVM(BVMT_createVM()))
end function

end namespace