
import "pkg:/source/rLog/rLogMixin.bs"
import "pkg:/source/maestro/observable/ObservableMixin.bs"
import "pkg:/source/maestro/view/viewModel/ViewModelMixin.bs"
import "pkg:/source/view/viewModels/MultiControlScreenVM.bs"

function Init()
  registerLogger("MultiControlScreen")
  M_createNodeVars() 
end function

'+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
'++ binding callbacks
'+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++


'+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
'++ Lifecycle methods
'+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

function initialize(args)
  m.vm = new MultiControlScreenVM()
  m.vm.initialize()
  initializeView(m.parentContainer)
  MVMM.initializeBindings(true)
  m.rect.addFields({"isHero": true})
  m.parentContainer.needsRecalulating = true
end function

function onGainedFocus(isSelfFocused)

  if isSelfFocused
    MVMM.onFocusIdChange(m.vm.focusId)
  end if

end function
